"""stage_10_ads

Revision ID: 3e27a5f41dd1
Revises: a42ab7efa520
Create Date: 2026-05-25 22:53:19.732999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e27a5f41dd1'
down_revision: Union[str, Sequence[str], None] = 'a42ab7efa520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('advertiser_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('cost_per_impression', sa.Numeric(precision=8, scale=4), server_default='0.01', nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'cancelled', name='campaignstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_campaigns_advertiser_id'), 'ad_campaigns', ['advertiser_id'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_date_end'), 'ad_campaigns', ['date_end'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_date_start'), 'ad_campaigns', ['date_start'], unique=False)
    op.create_index(op.f('ix_ad_campaigns_status'), 'ad_campaigns', ['status'], unique=False)
    op.create_table('ad_banners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('placement', sa.Enum('sidebar', 'top', 'inline', 'footer', name='bannerplacement'), nullable=False),
    sa.Column('target_animal_type_id', sa.UUID(), nullable=True),
    sa.Column('target_breed_id', sa.UUID(), nullable=True),
    sa.Column('target_region', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('impressions_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('clicks_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ad_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_animal_type_id'], ['animal_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_breed_id'], ['breeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_banners_campaign_id'), 'ad_banners', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ad_banners_placement'), 'ad_banners', ['placement'], unique=False)
    op.create_index('ix_ad_banners_serve', 'ad_banners', ['placement', 'is_active'], unique=False)
    op.create_table('ad_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('banner_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('impression', 'click', name='adeventtype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=128), nullable=True),
    sa.Column('page_url', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['ad_banners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ad_events_banner_created', 'ad_events', ['banner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ad_events_banner_id'), 'ad_events', ['banner_id'], unique=False)
    op.create_index(op.f('ix_ad_events_created_at'), 'ad_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ad_events_event_type'), 'ad_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_events_event_type'), table_name='ad_events')
    op.drop_index(op.f('ix_ad_events_created_at'), table_name='ad_events')
    op.drop_index(op.f('ix_ad_events_banner_id'), table_name='ad_events')
    op.drop_index('ix_ad_events_banner_created', table_name='ad_events')
    op.drop_table('ad_events')
    op.drop_index('ix_ad_banners_serve', table_name='ad_banners')
    op.drop_index(op.f('ix_ad_banners_placement'), table_name='ad_banners')
    op.drop_index(op.f('ix_ad_banners_campaign_id'), table_name='ad_banners')
    op.drop_table('ad_banners')
    op.drop_index(op.f('ix_ad_campaigns_status'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_date_start'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_date_end'), table_name='ad_campaigns')
    op.drop_index(op.f('ix_ad_campaigns_advertiser_id'), table_name='ad_campaigns')
    op.drop_table('ad_campaigns')
    # ### end Alembic commands ###
    # ДОПОЛНЕНО ВРУЧНУЮ: drop_type для PG-enum'ов. Без этого повторный
    # upgrade падает на "type X already exists".
    sa.Enum(name='adeventtype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='bannerplacement').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='campaignstatus').drop(op.get_bind(), checkfirst=True)
