"""stage_04_kennels_dogs_files

Revision ID: 55e42cedc4af
Revises: 8e3b86aa7b2f
Create Date: 2026-05-25 16:21:30.650384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e42cedc4af'
down_revision: Union[str, Sequence[str], None] = '8e3b86aa7b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    op.create_table('kennels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kennel_prefix', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('avatar_file_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kennel_prefix')
    )
    op.create_index(op.f('ix_kennels_city'), 'kennels', ['city'], unique=False)
    op.create_index(op.f('ix_kennels_name'), 'kennels', ['name'], unique=False)
    op.create_index(op.f('ix_kennels_owner_id'), 'kennels', ['owner_id'], unique=False)
    op.create_table('dogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kennel_id', sa.UUID(), nullable=True),
    sa.Column('breed_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sexenum'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('color', sa.String(length=128), nullable=True),
    sa.Column('rkf_number', sa.String(length=64), nullable=True),
    sa.Column('tattoo', sa.String(length=64), nullable=True),
    sa.Column('microchip', sa.String(length=32), nullable=True),
    sa.Column('father_id', sa.UUID(), nullable=True),
    sa.Column('mother_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['father_id'], ['dogs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kennel_id'], ['kennels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mother_id'], ['dogs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rkf_number')
    )
    op.create_index(op.f('ix_dogs_breed_id'), 'dogs', ['breed_id'], unique=False)
    op.create_index(op.f('ix_dogs_father_id'), 'dogs', ['father_id'], unique=False)
    op.create_index(op.f('ix_dogs_kennel_id'), 'dogs', ['kennel_id'], unique=False)
    op.create_index(op.f('ix_dogs_mother_id'), 'dogs', ['mother_id'], unique=False)
    op.create_index(op.f('ix_dogs_name'), 'dogs', ['name'], unique=False)
    op.create_table('dog_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dog_id', 'file_id', name='uq_dog_photo')
    )
    op.create_index(op.f('ix_dog_photos_dog_id'), 'dog_photos', ['dog_id'], unique=False)
    op.create_index(op.f('ix_dog_photos_file_id'), 'dog_photos', ['file_id'], unique=False)
    # ИСПРАВЛЕНО ВРУЧНУЮ: PostgreSQL не умеет автоматически кастовать
    # VARCHAR → UUID. На этапе 2 поле было плейсхолдером (String) и
    # данных в нём нет, поэтому делаем явный USING NULL::uuid — это
    # очищает столбец и меняет тип за одну операцию.
    op.alter_column(
        'users',
        'avatar_file_id',
        existing_type=sa.VARCHAR(length=255),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using='NULL::uuid',
    )
    # Явное имя constraint — иначе downgrade с drop_constraint(None) упадёт.
    op.create_foreign_key(
        'fk_users_avatar_file_id',
        'users',
        'files',
        ['avatar_file_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_avatar_file_id', 'users', type_='foreignkey')
    op.alter_column(
        'users',
        'avatar_file_id',
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
        postgresql_using='NULL::varchar',
    )
    op.drop_index(op.f('ix_dog_photos_file_id'), table_name='dog_photos')
    op.drop_index(op.f('ix_dog_photos_dog_id'), table_name='dog_photos')
    op.drop_table('dog_photos')
    op.drop_index(op.f('ix_dogs_name'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_mother_id'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_kennel_id'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_father_id'), table_name='dogs')
    op.drop_index(op.f('ix_dogs_breed_id'), table_name='dogs')
    op.drop_table('dogs')
    op.drop_index(op.f('ix_kennels_owner_id'), table_name='kennels')
    op.drop_index(op.f('ix_kennels_name'), table_name='kennels')
    op.drop_index(op.f('ix_kennels_city'), table_name='kennels')
    op.drop_table('kennels')
    op.drop_index(op.f('ix_files_uploaded_by'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
    # ДОПОЛНЕНО ВРУЧНУЮ (bug_243 audit 2026-05-28): SQLAlchemy.Enum в
    # PostgreSQL создаёт отдельный TYPE 'sexenum', который автогенератор
    # Alembic в downgrade не убирает. Без явного drop повторный upgrade
    # упадёт: "type already exists".
    sa.Enum(name='sexenum').drop(op.get_bind(), checkfirst=True)
