"""stage_03_references

Revision ID: 8e3b86aa7b2f
Revises: 41d02932e6d2
Create Date: 2026-05-25 11:15:05.367400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3b86aa7b2f'
down_revision: Union[str, Sequence[str], None] = '41d02932e6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_types_code'), 'animal_types', ['code'], unique=True)
    op.create_table('show_ranks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_ranks_code'), 'show_ranks', ['code'], unique=True)
    op.create_table('breed_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_type_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'code', name='uq_breed_group_code'),
    sa.UniqueConstraint('animal_type_id', 'number', name='uq_breed_group_number')
    )
    op.create_index(op.f('ix_breed_groups_animal_type_id'), 'breed_groups', ['animal_type_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_disqualifying', sa.Boolean(), nullable=False),
    sa.Column('is_puppy_grade', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'code', name='uq_grade_code')
    )
    op.create_index(op.f('ix_grades_animal_type_id'), 'grades', ['animal_type_id'], unique=False)
    op.create_table('show_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('age_from_months', sa.Integer(), nullable=False),
    sa.Column('age_to_months', sa.Integer(), nullable=True),
    sa.Column('can_receive_cac', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'code', name='uq_show_class_code')
    )
    op.create_index(op.f('ix_show_classes_animal_type_id'), 'show_classes', ['animal_type_id'], unique=False)
    op.create_table('titles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_type_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_reserve', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'code', name='uq_title_code')
    )
    op.create_index(op.f('ix_titles_animal_type_id'), 'titles', ['animal_type_id'], unique=False)
    op.create_table('breeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_type_id', sa.UUID(), nullable=False),
    sa.Column('breed_group_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fci_number', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['animal_type_id'], ['animal_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['breed_group_id'], ['breed_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_type_id', 'code', name='uq_breed_code')
    )
    op.create_index(op.f('ix_breeds_animal_type_id'), 'breeds', ['animal_type_id'], unique=False)
    op.create_index(op.f('ix_breeds_breed_group_id'), 'breeds', ['breed_group_id'], unique=False)
    op.create_index(op.f('ix_breeds_name'), 'breeds', ['name'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.drop_index(op.f('ix_breeds_name'), table_name='breeds')
    op.drop_index(op.f('ix_breeds_breed_group_id'), table_name='breeds')
    op.drop_index(op.f('ix_breeds_animal_type_id'), table_name='breeds')
    op.drop_table('breeds')
    op.drop_index(op.f('ix_titles_animal_type_id'), table_name='titles')
    op.drop_table('titles')
    op.drop_index(op.f('ix_show_classes_animal_type_id'), table_name='show_classes')
    op.drop_table('show_classes')
    op.drop_index(op.f('ix_grades_animal_type_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_breed_groups_animal_type_id'), table_name='breed_groups')
    op.drop_table('breed_groups')
    op.drop_index(op.f('ix_show_ranks_code'), table_name='show_ranks')
    op.drop_table('show_ranks')
    op.drop_index(op.f('ix_animal_types_code'), table_name='animal_types')
    op.drop_table('animal_types')
    # ### end Alembic commands ###
