"""stage_05_litters_classifieds

Revision ID: 9357e3441b8e
Revises: 55e42cedc4af
Create Date: 2026-05-25 16:38:12.678404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9357e3441b8e'
down_revision: Union[str, Sequence[str], None] = '55e42cedc4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('litters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kennel_id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=False),
    sa.Column('father_id', sa.UUID(), nullable=True),
    sa.Column('mother_id', sa.UUID(), nullable=True),
    sa.Column('born_at', sa.Date(), nullable=True),
    sa.Column('puppies_count', sa.Integer(), nullable=True),
    sa.Column('males_count', sa.Integer(), nullable=True),
    sa.Column('females_count', sa.Integer(), nullable=True),
    sa.Column('price_from', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_to', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('planned', 'born', 'available', 'sold_out', 'archived', name='litterstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['father_id'], ['dogs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['kennel_id'], ['kennels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mother_id'], ['dogs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_litters_breed_id'), 'litters', ['breed_id'], unique=False)
    op.create_index(op.f('ix_litters_father_id'), 'litters', ['father_id'], unique=False)
    op.create_index(op.f('ix_litters_kennel_id'), 'litters', ['kennel_id'], unique=False)
    op.create_index(op.f('ix_litters_mother_id'), 'litters', ['mother_id'], unique=False)
    op.create_index(op.f('ix_litters_status'), 'litters', ['status'], unique=False)
    op.create_table('classifieds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('puppy_sale', 'adult_sale', 'mating', 'handler', 'grooming', 'other', name='classifiedcategory'), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('litter_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('active', 'moderation', 'closed', 'archived', name='classifiedstatus'), nullable=False),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['litter_id'], ['litters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifieds_author_id'), 'classifieds', ['author_id'], unique=False)
    op.create_index(op.f('ix_classifieds_breed_id'), 'classifieds', ['breed_id'], unique=False)
    op.create_index(op.f('ix_classifieds_category'), 'classifieds', ['category'], unique=False)
    op.create_index(op.f('ix_classifieds_city'), 'classifieds', ['city'], unique=False)
    op.create_index(op.f('ix_classifieds_litter_id'), 'classifieds', ['litter_id'], unique=False)
    op.create_index('ix_classifieds_search_vector', 'classifieds', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_classifieds_status'), 'classifieds', ['status'], unique=False)
    op.create_index('ix_classifieds_status_category', 'classifieds', ['status', 'category'], unique=False)
    op.create_table('classified_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('classified_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['classified_id'], ['classifieds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classified_id', 'file_id', name='uq_classified_image')
    )
    op.create_index(op.f('ix_classified_images_classified_id'), 'classified_images', ['classified_id'], unique=False)
    op.create_index(op.f('ix_classified_images_file_id'), 'classified_images', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classified_images_file_id'), table_name='classified_images')
    op.drop_index(op.f('ix_classified_images_classified_id'), table_name='classified_images')
    op.drop_table('classified_images')
    op.drop_index('ix_classifieds_status_category', table_name='classifieds')
    op.drop_index(op.f('ix_classifieds_status'), table_name='classifieds')
    op.drop_index('ix_classifieds_search_vector', table_name='classifieds', postgresql_using='gin')
    op.drop_index(op.f('ix_classifieds_litter_id'), table_name='classifieds')
    op.drop_index(op.f('ix_classifieds_city'), table_name='classifieds')
    op.drop_index(op.f('ix_classifieds_category'), table_name='classifieds')
    op.drop_index(op.f('ix_classifieds_breed_id'), table_name='classifieds')
    op.drop_index(op.f('ix_classifieds_author_id'), table_name='classifieds')
    op.drop_table('classifieds')
    op.drop_index(op.f('ix_litters_status'), table_name='litters')
    op.drop_index(op.f('ix_litters_mother_id'), table_name='litters')
    op.drop_index(op.f('ix_litters_kennel_id'), table_name='litters')
    op.drop_index(op.f('ix_litters_father_id'), table_name='litters')
    op.drop_index(op.f('ix_litters_breed_id'), table_name='litters')
    op.drop_table('litters')
    # ### end Alembic commands ###
    # ДОПОЛНЕНО ВРУЧНУЮ: SQLAlchemy.Enum в PostgreSQL создаёт отдельный
    # TYPE, который автогенератор Alembic в downgrade не убирает.
    # Без явного drop_type повторный upgrade упадёт: "type already exists".
    sa.Enum(name='classifiedstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='classifiedcategory').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='litterstatus').drop(op.get_bind(), checkfirst=True)
