"""stage_06_shows_management

Revision ID: a2d7b35eb3fc
Revises: 9357e3441b8e
Create Date: 2026-05-25 18:23:15.469911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2d7b35eb3fc'
down_revision: Union[str, Sequence[str], None] = '9357e3441b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('rank_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('entry_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'registration_open', 'registration_closed', 'in_progress', 'completed', 'cancelled', name='showstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rank_id'], ['show_ranks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_city'), 'shows', ['city'], unique=False)
    op.create_index(op.f('ix_shows_date_start'), 'shows', ['date_start'], unique=False)
    op.create_index(op.f('ix_shows_name'), 'shows', ['name'], unique=False)
    op.create_index(op.f('ix_shows_organizer_id'), 'shows', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_shows_rank_id'), 'shows', ['rank_id'], unique=False)
    op.create_index(op.f('ix_shows_status'), 'shows', ['status'], unique=False)
    op.create_table('show_breeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'breed_id', name='uq_show_breed')
    )
    op.create_index(op.f('ix_show_breeds_breed_id'), 'show_breeds', ['breed_id'], unique=False)
    op.create_index(op.f('ix_show_breeds_show_id'), 'show_breeds', ['show_id'], unique=False)
    op.create_table('show_judges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('judge_id', sa.UUID(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('breed_group_id', sa.UUID(), nullable=True),
    sa.CheckConstraint('(breed_id IS NOT NULL AND breed_group_id IS NULL) OR (breed_id IS NULL AND breed_group_id IS NOT NULL)', name='ck_show_judge_target'),
    sa.ForeignKeyConstraint(['breed_group_id'], ['breed_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'judge_id', 'breed_group_id', name='uq_show_judge_group'),
    sa.UniqueConstraint('show_id', 'judge_id', 'breed_id', name='uq_show_judge_breed')
    )
    op.create_index(op.f('ix_show_judges_breed_group_id'), 'show_judges', ['breed_group_id'], unique=False)
    op.create_index(op.f('ix_show_judges_breed_id'), 'show_judges', ['breed_id'], unique=False)
    op.create_index(op.f('ix_show_judges_judge_id'), 'show_judges', ['judge_id'], unique=False)
    op.create_index(op.f('ix_show_judges_show_id'), 'show_judges', ['show_id'], unique=False)
    op.create_table('show_rings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('ring_number', sa.Integer(), nullable=False),
    sa.Column('breed_id', sa.UUID(), nullable=True),
    sa.Column('breed_group_id', sa.UUID(), nullable=True),
    sa.Column('show_class_id', sa.UUID(), nullable=True),
    sa.Column('judge_id', sa.UUID(), nullable=True),
    sa.Column('ring_date', sa.Date(), nullable=True),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['breed_group_id'], ['breed_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_class_id'], ['show_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_rings_breed_group_id'), 'show_rings', ['breed_group_id'], unique=False)
    op.create_index(op.f('ix_show_rings_breed_id'), 'show_rings', ['breed_id'], unique=False)
    op.create_index(op.f('ix_show_rings_show_class_id'), 'show_rings', ['show_class_id'], unique=False)
    op.create_index(op.f('ix_show_rings_show_id'), 'show_rings', ['show_id'], unique=False)
    op.create_table('show_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('show_id', sa.UUID(), nullable=False),
    sa.Column('dog_id', sa.UUID(), nullable=False),
    sa.Column('show_class_id', sa.UUID(), nullable=False),
    sa.Column('handler_id', sa.UUID(), nullable=True),
    sa.Column('registered_by', sa.UUID(), nullable=False),
    sa.Column('catalog_number', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dog_id'], ['dogs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_class_id'], ['show_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('show_id', 'catalog_number', name='uq_show_entry_catalog'),
    sa.UniqueConstraint('show_id', 'dog_id', name='uq_show_entry_dog')
    )
    op.create_index(op.f('ix_show_entries_dog_id'), 'show_entries', ['dog_id'], unique=False)
    op.create_index(op.f('ix_show_entries_registered_by'), 'show_entries', ['registered_by'], unique=False)
    op.create_index(op.f('ix_show_entries_show_class_id'), 'show_entries', ['show_class_id'], unique=False)
    op.create_index(op.f('ix_show_entries_show_id'), 'show_entries', ['show_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_entries_show_id'), table_name='show_entries')
    op.drop_index(op.f('ix_show_entries_show_class_id'), table_name='show_entries')
    op.drop_index(op.f('ix_show_entries_registered_by'), table_name='show_entries')
    op.drop_index(op.f('ix_show_entries_dog_id'), table_name='show_entries')
    op.drop_table('show_entries')
    op.drop_index(op.f('ix_show_rings_show_id'), table_name='show_rings')
    op.drop_index(op.f('ix_show_rings_show_class_id'), table_name='show_rings')
    op.drop_index(op.f('ix_show_rings_breed_id'), table_name='show_rings')
    op.drop_index(op.f('ix_show_rings_breed_group_id'), table_name='show_rings')
    op.drop_table('show_rings')
    op.drop_index(op.f('ix_show_judges_show_id'), table_name='show_judges')
    op.drop_index(op.f('ix_show_judges_judge_id'), table_name='show_judges')
    op.drop_index(op.f('ix_show_judges_breed_id'), table_name='show_judges')
    op.drop_index(op.f('ix_show_judges_breed_group_id'), table_name='show_judges')
    op.drop_table('show_judges')
    op.drop_index(op.f('ix_show_breeds_show_id'), table_name='show_breeds')
    op.drop_index(op.f('ix_show_breeds_breed_id'), table_name='show_breeds')
    op.drop_table('show_breeds')
    op.drop_index(op.f('ix_shows_status'), table_name='shows')
    op.drop_index(op.f('ix_shows_rank_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_organizer_id'), table_name='shows')
    op.drop_index(op.f('ix_shows_name'), table_name='shows')
    op.drop_index(op.f('ix_shows_date_start'), table_name='shows')
    op.drop_index(op.f('ix_shows_city'), table_name='shows')
    op.drop_table('shows')
    # ### end Alembic commands ###
    # ДОПОЛНЕНО ВРУЧНУЮ: убрать enum-тип после удаления таблиц, иначе
    # повторный upgrade падает на "type showstatus already exists".
    sa.Enum(name='showstatus').drop(op.get_bind(), checkfirst=True)
