"""stage_14_moderation_logs

Revision ID: b9929c474916
Revises: b713639e179a
Create Date: 2026-05-26 11:12:53.874651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9929c474916'
down_revision: Union[str, Sequence[str], None] = 'b713639e179a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_logs_action'), 'moderation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_moderation_logs_actor_id'), 'moderation_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_created_at'), 'moderation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_moderation_logs_target_id'), 'moderation_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_moderation_logs_target_type'), 'moderation_logs', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moderation_logs_target_type'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_target_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_created_at'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_actor_id'), table_name='moderation_logs')
    op.drop_index(op.f('ix_moderation_logs_action'), table_name='moderation_logs')
    op.drop_table('moderation_logs')
    # ### end Alembic commands ###
