"""stage_12_kennel_verified

Revision ID: c422d1b5ae97
Revises: 3e27a5f41dd1
Create Date: 2026-05-25 23:29:37.693965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c422d1b5ae97'
down_revision: Union[str, Sequence[str], None] = '3e27a5f41dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kennels', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kennels', 'is_verified')
    # ### end Alembic commands ###
